### PR TITLE
Fix FSE+UTextView

### PR DESCRIPTION
**Pull request by NikitaAsabin**
Fix text view top inset

### CODE REVIEW

**Comment by kruperfone** [comment]
👍 💣

**Comment by nikitafomin** [comment]
this is really something new in iOS development! I would kiss your code if I could 💋 💻

**Comment by ZalyalovIldar** [comment]
awesome! 👍

**Comment by vladimirgoncharov** [comment]
this is a magic! 👍

**Comment by EllinaKuznetcova** [comment]
Amazing!
Wonderful!
Glorious!
Magnificent!
👍

**Comment by NikitaAsabin** [comment]
Oh thanks my friends. It's really greatest PR in my life. Thanks for you all again! 💃

**Pull request merged**
